pipeline {
    agent any

    tools {
        // This 'maven' corresponds to the name of the Maven installation in Jenkins' Global Tool Configuration.
        maven 'maven-3'
    }


    environment {
        // Use your GHCR repository name
        DOCKER_IMAGE = 'ghcr.io/satyanarayana-senapathi/jenkins-test:latest'
        GHCR_TOKEN = credentials('GHCR-TOKEN-ID')
    }

    stages {
        stage('Build with Maven') {
            steps {
                script {
                    sh 'mvn clean install -f ./spring-boot-assignment'
                    sh 'sudo docker --version'
                }
            }
        }
        
        stage('Build Docker image') {
            steps {
                script {
                    sh "sudo docker build -t ${DOCKER_IMAGE} -f ./spring-boot-assignment/Dockerfile ./spring-boot-assignment"
                }
            }
        }
        stage('GHCR Login ') {
            steps {
                   sh 'echo $GHCR_TOKEN_PSW | sudo docker login ghcr.io -u $GHCR_TOKEN_USR --password-stdin'
                    sh "sudo docker push ${DOCKER_IMAGE}"
                }
            }
        stage('Deploy to EC2 from GitHub Packages') {
        steps {
            withCredentials([sshUserPrivateKey(credentialsId: 'SSH_KEY', keyFileVariable: 'SSH_KEY')]) {
                script {
                    sh '''
                        ssh -i $SSH_KEY -o StrictHostKeyChecking=no ubuntu@ec2-54-197-119-229.compute-1.amazonaws.com '
                        docker login ghcr.io -u $GHCR_TOKEN_USR -p $GHCR_TOKEN_PSW && \
                        docker stop frontend || true && \
                        docker rm frontend || true && \
                        docker rmi ghcr.io/$GITHUB_USER/jenkins-test:latest -f || true && \
                        docker pull ghcr.io/$GITHUB_USER/jenkins-test:latest && \
                        docker run --name frontend -d -p 8081:8080 ghcr.io/$GITHUB_USER/jenkins-test:latest && \
                        docker logout ghcr.io'
                    '''
                            }
                        }
                }
            }
        } 
}
