name: artifacts
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build" > log.txt
      - name: Share log file
        uses: actions/upload-artifact@v2
        with:
            name: log
            path: log.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Download log file
        uses: actions/download-artifact@v2
        with:
          name: log
      - name: printing log
        run: cat log.txt
