name: artifacts
on: 
  push:
    paths:
      - '.github/workflows/artifact.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into remote server
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
            USER: ${{ secrets.USER }}
            HOSTNAME : ${{ secrets.HOSTNAME }}
        run: |
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id
            chmod 777 ~/.ssh/id
            ssh -o StrictHostKeyChecking=no $USER@$HOSTNAME "
            whoami
            ls -al
            "
