# name: Deploy to AWS EC2

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 14
      
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: satyanarayanasvv/react-app:${{ github.sha }}
#           dockerfile: Dockerfile
        
#       - name: SSH into EC2 instance and pull Docker image
#         run: |
#             ssh -o StrictHostKeyChecking=no -i '${{ secrets.EC2_PRIVATE_KEY }}' ubuntu@ec2-13-233-116-175.ap-south-1.compute.amazonaws.com            
#             sudo apt install nginx -y

name: docker image + pull from ec2
on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Build application
        run: |
          cd my-app
          npm run build

      - name: run tests
        run: |
          cd my-app
          npm run test
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./my-app
          push: true
          tags: satyanarayanasvv/react-app:${{ github.sha }}
          dockerfile: Dockerfile

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker pull satyanarayanasvv/react-app
          
      
