name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: <AWS_ECR_REGISTRY>/<IMAGE_NAME>:latest
          dockerfile: Dockerfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <AWS_REGION>

      - name: SSH into EC2 instance and pull Docker image
        run: |
          ssh -o StrictHostKeyChecking=no -i <PATH_TO_SSH_PRIVATE_KEY> <EC2_INSTANCE_USERNAME>@<EC2_INSTANCE_IP> << EOF
            docker stop <CONTAINER_NAME> || true
            docker rm <CONTAINER_NAME> || true
            docker pull <AWS_ECR_REGISTRY>/<IMAGE_NAME>:latest
            docker run -d -p <HOST_PORT>:<CONTAINER_PORT> --name <CONTAINER_NAME> <AWS_ECR_REGISTRY>/<IMAGE_NAME>:latest
          EOF
