
name: Deploy to AWS EC2

on:
  push:
    paths:
      - 'my-app/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .my-app
          push: true
          tags: satyanarayanasvv/react-app:${{ github.sha }}
          dockerfile: Dockerfile

      - name: SSH into remote server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }} 
          github_sha: ${{ github.sha }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_private_key
          chmod 600 ssh_private_key
          ssh -i ssh_private_key -o StrictHostKeyChecking=no ubuntu@ec2-3-111-168-160.ap-south-1.compute.amazonaws.com
          sudo docker run -d -p  80:3000 satyanarayanasvv/react-app:$github_sha
           
