name: Hello World

on: 
  pull_request:
    branches:
      -main

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello, World!"
