name: packages-push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn clean install -DskipTests

        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITPASS }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./spring-boot-assignment
          push: true
          tags: ghcr.io/${{ github.actor }}/springapp:1.0
