name: Deploy from GHCR to AWS EC2

on:
  push:
    paths:
      - 'spring-boot-app/**'
      - '.github/workflows/package-ec2-deploy.yml'
 

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spring-boot-assignment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' 
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITPASS }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/satyanarayana-zemoso/spring-boot-app:${{ github.run_number }}
          dockerfile: Dockerfile


      - name: SSH into remote server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }} 
          RUN_NUMBER: ${{ github.run_number }}
          AWS_DNS : ${{ secrets.AWS_USER }}
          USERNAME: ${{ github.actor }}
          PAT: ${{ secrets.GITPASS }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/ssh_private_key
          chmod 400 ~/ssh_private_key
          ssh -i ~/ssh_private_key -o StrictHostKeyChecking=no ubuntu@$AWS_DNS '
            echo $PAT | docker login ghcr.io -u $USERNAME --password-stdin 
            docker pull ghcr.io/satyanarayana-zemoso/spring-boot-app:$RUN_NUMBER
            docker logout ghcr.io
          '
