# This is a basic workflow to help you get started with Actions

name: working with strategies

on:
  # push:
  #   branches: [ "main" ]
  push:
    paths:
      - '.github/workflows/strategy.yml'
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 

